modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="eternal_heart"
version="${mod_version}"
displayName="eternal_heart-永恒之心"
logoFile="eternal_heart_logo.png"
description="还原泰拉瑞亚 Fargo魂石模组「永恒之魂」的终极饰品。需 MineFargo 作为前置。可选集成：FTB Ultimine（连锁挖掘）、Caelus（鞘翅飞行）、AttributeFix（解除血量上限）。"
authors=["Adapted from Inolia_Zaicek's MineFargo"]

[[dependencies.eternal_heart]]
    modId="forge"
    mandatory=true
    versionRange="[47.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="curios"
    mandatory=true
    versionRange="[5.14,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="mine_fargo"
    mandatory=${mine_fargo_mandatory}
    versionRange="[1.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="ftbultimine"
    mandatory=false
    versionRange="[2001,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="caelus"
    mandatory=false
    versionRange="[3.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eternal_heart]]
    modId="attributefix"
    mandatory=false
    versionRange="[21,)"
    ordering="AFTER"
    side="BOTH"
